### ISSUE TITLE
Receiving Event is causing error

### ISSUE THREAD

**Issue by srbartlett** [johnagan/tinyspeck#2]
Likely to be due to a misconfiguration.... I was hoping you could point me in the right direction.

The following payload is being sent by Slack which is causing an error to be throw

```
{
    "token": "xxxxxxxxxx",
    "team_id": "xxxx",
    "api_app_id": "xxx",
    "event": {
        "type": "reaction_added",
        "user": "xx",
        "item": {
            "type": "message",
            "channel": "C1DRDB86N",
            "ts": "1464916417.000004"
        },
        "reaction": "grinning",
        "item_user": "U145BQU4Q",
        "event_ts": "1472035990.715774"
    },
    "type": "event_callback",
    "authed_users": [
        "U12R695EC"
    ]
}
```

```
if (this.eventNames().indexOf(req.url.pathname) !== -1) {
                 ^
TypeError: this.eventNames is not a function
    at IncomingMessage.<anonymous> (/Users/xxxx/slack/onboarding-example/node_modules/tinyspeck/index.js:195:18)
    at emitNone (events.js:68:13)
    at IncomingMessage.emit (events.js:167:7)
    at endReadableNT (_stream_readable.js:906:12)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)
```

**Comment by srbartlett** [comment]
Appears I need Node v6 

No probs.

**Comment by johnagan** [comment]
correct. I should add the `engines` sections to `package.json`
